[build]
  command = "npm run build"
  publish = "dist"

  [build.environment]
    NODE_VERSION = "20"
    VITE_API_BASE_URL = "https://yoga-2-i5oy.onrender.com/api"
    VITE_EMAILJS_SERVICE_ID = "service_8eusket"
    VITE_EMAILJS_TEMPLATE_ID = "template_a3wn0ko"
    VITE_EMAILJS_PUBLIC_KEY = "Lq-b9zkDDo2as94ms"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
